name: CD

on:
  workflow_run:
    workflows:
      - CI # Nome exato do workflow CI
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull guugs/atv:latest

      - name: Stop Docker container
        run: docker stop ci || true

      - name: Remove Docker container
        run: docker rm ci || true

      - name: Run Docker container
        run: docker run --name ci -d -p 8080:8080 guugs/atv:latest
