name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull guugs/forum-kt:latest

      - name: Stop Docker container
        run: docker stop ci || true

      - name: Remove Docker container
        run: docker rm ci || true

      - name: Run Docker container
        run: docker run --name ci -d -p 8080:8080 guugs/forum-kt:latest
