name: Deploy to EC2

on:
  push:
    branches:
      - main # Executa o workflow apenas quando há push na branch "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  build-and-publish-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-api:${{ github.sha }} .

      - name: Push Docker image
        run: docker push my-api:${{ github.sha }}

  deploy-to-ec2:
    needs: build-and-publish-docker
    runs-on: self-hosted # Configurado para rodar no GitHub Runner na EC2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker image on EC2
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull my-api:${{ github.sha }}

      - name: Stop and remove existing container
        run: |
          docker stop my-api || true
          docker rm my-api || true

      - name: Run new container
        run: |
          docker run -d \
            --name my-api \
            -p 8080:8080 \
            my-api:${{ github.sha }}
